//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLTECH.Models
{
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
        }

        public PagedList<Sanpham> Sanphams { get; set; }
        public int Masp { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string Tensp { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [Range(1000, Int32.MaxValue, ErrorMessage = "Giá tiền không được nhỏ hơn 1000")]
        public Nullable<decimal> Giatien { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Số lượng không được nhỏ hơn 1")]
        public Nullable<int> Soluong { get; set; }
        public string Mota { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Thẻ sim không được nhỏ hơn 1")]
        public Nullable<int> Thesim { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Bộ nhớ trong không được nhỏ hơn 1")]
        public Nullable<int> Bonhotrong { get; set; }
        public Nullable<bool> Sanphammoi { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Ram không được nhỏ hơn 1")]
        public Nullable<int> Ram { get; set; }
        public string Anhbia { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public Nullable<int> Mahang { get; set; }
        public Nullable<int> Mahdh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual Hangsanxuat Hangsanxuat { get; set; }
        public virtual Hedieuhanh Hedieuhanh { get; set; }
    }
}
